Check for local autobrew script

diff --git a/r/configure b/r/configure
--- a/r/configure
+++ b/r/configure
@@ -63,9 +63,13 @@ else
         BREWDIR=$(brew --prefix)
       else
         echo "Downloading ${PKG_BREW_NAME}"
-        curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > autobrew
-        if [ $? -ne 0 ]; then
-          echo "Failed to download manifest for ${PKG_BREW_NAME}"
+        if [ -f "autobrew" ]; then
+          echo "Using local manifest for ${PKG_BREW_NAME}"
+        else
+          curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > autobrew
+          if [ $? -ne 0 ]; then
+            echo "Failed to download manifest for ${PKG_BREW_NAME}"
+          fi
         fi
         source autobrew
         if [ $? -ne 0 ]; then
