GH-48904: [C++][FlightRPC][CI][Packaging] Upload ODBC installer into GitHub release as RC (#48934)
### Rationale for this change
#48904 

Upload ODBC as a GitHub draft release upon release candidate tag

### What changes are included in this PR?
- Create a draft GitHub release for ODBC, and upload the ODBC MSI to the draft release. ODBC release is only triggered by RC tag
- add gh release ODBC download pattern to `04-binary-download.sh`
- add gh release ODBC upload pattern to `05-binary-upload.sh`

### Are these changes tested?
- CI changes tested in forked repository, a draft GitHub release is created
- `04-binary-download.sh` and `05-binary-upload.sh` changes are not tested
### Are there any user-facing changes?
Yes, this PR adds GitHub release for Apache Arrow Flight SQL ODBC MSI installer. 
* GitHub Issue: #48904

Lead-authored-by: Alina (Xi) Li <alina.li@improving.com>
Co-authored-by: Alina (Xi) Li <alinal@bitquilltech.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>

diff --git a/.github/workflows/cpp_extra.yml b/.github/workflows/cpp_extra.yml
--- a/.github/workflows/cpp_extra.yml
+++ b/.github/workflows/cpp_extra.yml
@@ -530,8 +530,43 @@ jobs:
         uses: actions/upload-artifact@v6
         with:
           name: flight-sql-odbc-msi-installer
-          path: build/cpp/Apache Arrow Flight SQL ODBC-*-win64.msi
+          path: build/cpp/Apache-Arrow-Flight-SQL-ODBC-*-win64.msi
           if-no-files-found: error
+      - name: Install ODBC MSI
+        run: |
+          cd build/cpp
+          $odbc_msi = Get-ChildItem -Filter "Apache-Arrow-Flight-SQL-ODBC-*-win64.msi"
+          if (-not $odbc_msi) {
+            Write-Error "ODBC MSI not found"
+            exit 1
+          }
+
+          foreach ($msi in $odbc_msi) {
+            Write-Host "Installing $($msi.Name) with logs"
+            $log = "odbc-install.log"
+            Start-Process msiexec.exe -Wait -ArgumentList "/i `"$msi`"", "/qn", "/L*V `"$log`""
+            Get-Content $log
+          }
+      - name: Check ODBC DLL installation
+        run: |
+          $dirs = Get-ChildItem "C:\Program Files" -Directory -Filter "Apache-Arrow-Flight-SQL-ODBC*"
+
+          foreach ($dir in $dirs) {
+            $bin = Join-Path $dir.FullName "bin"
+
+            if (Test-Path $bin) {
+              tree $bin /f
+
+              $dll = Join-Path $bin "arrow_flight_sql_odbc.dll"
+              if (Test-Path $dll) {
+                Write-Host "Found ODBC DLL: $dll"
+                exit 0
+              }
+            }
+          }
+
+          Write-Error "ODBC DLL not found"
+          exit 1
 
   odbc-nightly:
     needs: odbc-msvc
@@ -578,6 +613,39 @@ jobs:
           remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
           remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
           remote_host_key: ${{ secrets.NIGHTLIES_RSYNC_HOST_KEY }}
+
+  odbc-release:
+    needs: odbc-msvc
+    name: ODBC release
+    runs-on: ubuntu-latest
+    if: ${{ startsWith(github.ref_name, 'apache-arrow-') && contains(github.ref_name, '-rc') }}
+    permissions:
+      # Upload to GitHub Release
+      contents: write
+    steps:
+      - name: Checkout Arrow
+        uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+          submodules: recursive
+      - name: Download the artifacts
+        uses: actions/download-artifact@v7
+        with:
+          name: flight-sql-odbc-msi-installer
+      - name: Wait for creating GitHub Release
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          dev/release/utils-watch-gh-workflow.sh \
+            ${GITHUB_REF_NAME} \
+            release_candidate.yml
+      - name: Upload the artifacts to GitHub Release
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh release upload ${GITHUB_REF_NAME} \
+            --clobber \
+            Apache-Arrow-Flight-SQL-ODBC-*-win64.msi
 
   report-extra-cpp:
     if: github.event_name == 'schedule' && always()
